### PR TITLE
Create call of duty infintie warfare

### PR DESCRIPTION
**Pull request by DXRR1cKy321**

### CODE REVIEW

**Comment by skkuull** [comment]
?

**Comment by CrazyCSIW6** [comment]
lolwut

**Comment by CrazyCSIW6** [comment]
blud really said "call of duty infintie warfare"

**Comment by tildecharlotte** [comment]
Like, from scratch or...?

**Comment by zabersan** [comment]
> blud really said "call of duty infintie warfare"

bro really on that Infinite Welfare 😭

**Pull request closed without merging**
